export const images = {
  bee: require("./bee.png"),
  ellipse: require("./ellipse.png"),
  clock: require("./clock.png"),
  security: require("./security.png"),
  coin: require("./coin.png"),
  plus: require("./plus.png"),
  lines:require('./line.png'),
  seat:require('./seat.png'),
  eye:require('./eye.png'),
  arrowback:require('./left-arrow.png'),
  next:require('./next.png'),
  plus2:require('./plus2.png'),
  questions:require('./question.png'),
  filter:require('./filter.png'),
  location:require('./loaction.png'),
  strelka:require('./strelka.png'),
  globe:require('./globe.png'),
  restangle:require('./restangle.png'),
  blackrestangle:require('./blackrestangle.png')
};
